'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WSCorreios
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WSCorreios.CalcPrecoPrazoWSSoap")>  _
    Public Interface CalcPrecoPrazoWSSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPrecoPrazo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CalcPrecoPrazo(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String) As WSCorreios.cResultado
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPrecoPrazoData", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CalcPrecoPrazoData(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal sDtCalculo As String) As WSCorreios.cResultado
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPrecoPrazoRestricao", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CalcPrecoPrazoRestricao(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal sDtCalculo As String) As WSCorreios.cResultado
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPreco", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CalcPreco(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String) As WSCorreios.cResultado
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPrecoData", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CalcPrecoData(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal sDtCalculo As String) As WSCorreios.cResultado
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPrazo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CalcPrazo(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String) As WSCorreios.cResultado
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPrazoData", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CalcPrazoData(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal sDtCalculo As String) As WSCorreios.cResultado
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPrazoRestricao", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CalcPrazoRestricao(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal sDtCalculo As String) As WSCorreios.cResultado
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcPrecoFAC", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CalcPrecoFAC(ByVal nCdServico As String, ByVal nVlPeso As String, ByVal strDataCalculo As String) As WSCorreios.cResultado
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CalcDataMaxima", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CalcDataMaxima(ByVal codigoObjeto As String) As WSCorreios.cResultadoObjeto
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListaServicos", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ListaServicos() As WSCorreios.cResultadoServicos
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListaServicosSTAR", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ListaServicosSTAR() As WSCorreios.cResultadoServicos
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/VerificaModal", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function VerificaModal(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String) As WSCorreios.cResultadoModal
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getVersao", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getVersao() As WSCorreios.versao
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class cResultado
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private servicosField() As cServico
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property Servicos() As cServico()
            Get
                Return Me.servicosField
            End Get
            Set
                Me.servicosField = value
                Me.RaisePropertyChanged("Servicos")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class cServico
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoField As Integer
        
        Private valorField As String
        
        Private prazoEntregaField As String
        
        Private valorMaoPropriaField As String
        
        Private valorAvisoRecebimentoField As String
        
        Private valorValorDeclaradoField As String
        
        Private entregaDomiciliarField As String
        
        Private entregaSabadoField As String
        
        Private erroField As String
        
        Private msgErroField As String
        
        Private valorSemAdicionaisField As String
        
        Private obsFimField As String
        
        Private dataMaxEntregaField As String
        
        Private horaMaxEntregaField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Codigo() As Integer
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
                Me.RaisePropertyChanged("Codigo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Valor() As String
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
                Me.RaisePropertyChanged("Valor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property PrazoEntrega() As String
            Get
                Return Me.prazoEntregaField
            End Get
            Set
                Me.prazoEntregaField = value
                Me.RaisePropertyChanged("PrazoEntrega")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property ValorMaoPropria() As String
            Get
                Return Me.valorMaoPropriaField
            End Get
            Set
                Me.valorMaoPropriaField = value
                Me.RaisePropertyChanged("ValorMaoPropria")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property ValorAvisoRecebimento() As String
            Get
                Return Me.valorAvisoRecebimentoField
            End Get
            Set
                Me.valorAvisoRecebimentoField = value
                Me.RaisePropertyChanged("ValorAvisoRecebimento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property ValorValorDeclarado() As String
            Get
                Return Me.valorValorDeclaradoField
            End Get
            Set
                Me.valorValorDeclaradoField = value
                Me.RaisePropertyChanged("ValorValorDeclarado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property EntregaDomiciliar() As String
            Get
                Return Me.entregaDomiciliarField
            End Get
            Set
                Me.entregaDomiciliarField = value
                Me.RaisePropertyChanged("EntregaDomiciliar")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property EntregaSabado() As String
            Get
                Return Me.entregaSabadoField
            End Get
            Set
                Me.entregaSabadoField = value
                Me.RaisePropertyChanged("EntregaSabado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property Erro() As String
            Get
                Return Me.erroField
            End Get
            Set
                Me.erroField = value
                Me.RaisePropertyChanged("Erro")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property MsgErro() As String
            Get
                Return Me.msgErroField
            End Get
            Set
                Me.msgErroField = value
                Me.RaisePropertyChanged("MsgErro")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property ValorSemAdicionais() As String
            Get
                Return Me.valorSemAdicionaisField
            End Get
            Set
                Me.valorSemAdicionaisField = value
                Me.RaisePropertyChanged("ValorSemAdicionais")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property obsFim() As String
            Get
                Return Me.obsFimField
            End Get
            Set
                Me.obsFimField = value
                Me.RaisePropertyChanged("obsFim")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property DataMaxEntrega() As String
            Get
                Return Me.dataMaxEntregaField
            End Get
            Set
                Me.dataMaxEntregaField = value
                Me.RaisePropertyChanged("DataMaxEntrega")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=13)>  _
        Public Property HoraMaxEntrega() As String
            Get
                Return Me.horaMaxEntregaField
            End Get
            Set
                Me.horaMaxEntregaField = value
                Me.RaisePropertyChanged("HoraMaxEntrega")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class versao
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private versaoAtualField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property versaoAtual() As String
            Get
                Return Me.versaoAtualField
            End Get
            Set
                Me.versaoAtualField = value
                Me.RaisePropertyChanged("versaoAtual")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class cModal
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoField As String
        
        Private modalField As String
        
        Private obsField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
                Me.RaisePropertyChanged("codigo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property modal() As String
            Get
                Return Me.modalField
            End Get
            Set
                Me.modalField = value
                Me.RaisePropertyChanged("modal")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property obs() As String
            Get
                Return Me.obsField
            End Get
            Set
                Me.obsField = value
                Me.RaisePropertyChanged("obs")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class cResultadoModal
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private servicosModalField() As cModal
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property ServicosModal() As cModal()
            Get
                Return Me.servicosModalField
            End Get
            Set
                Me.servicosModalField = value
                Me.RaisePropertyChanged("ServicosModal")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class cServicosCalculo
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoField As String
        
        Private descricaoField As String
        
        Private calcula_precoField As String
        
        Private calcula_prazoField As String
        
        Private erroField As String
        
        Private msgErroField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
                Me.RaisePropertyChanged("codigo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property descricao() As String
            Get
                Return Me.descricaoField
            End Get
            Set
                Me.descricaoField = value
                Me.RaisePropertyChanged("descricao")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property calcula_preco() As String
            Get
                Return Me.calcula_precoField
            End Get
            Set
                Me.calcula_precoField = value
                Me.RaisePropertyChanged("calcula_preco")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property calcula_prazo() As String
            Get
                Return Me.calcula_prazoField
            End Get
            Set
                Me.calcula_prazoField = value
                Me.RaisePropertyChanged("calcula_prazo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property erro() As String
            Get
                Return Me.erroField
            End Get
            Set
                Me.erroField = value
                Me.RaisePropertyChanged("erro")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property msgErro() As String
            Get
                Return Me.msgErroField
            End Get
            Set
                Me.msgErroField = value
                Me.RaisePropertyChanged("msgErro")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class cResultadoServicos
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private servicosCalculoField() As cServicosCalculo
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property ServicosCalculo() As cServicosCalculo()
            Get
                Return Me.servicosCalculoField
            End Get
            Set
                Me.servicosCalculoField = value
                Me.RaisePropertyChanged("ServicosCalculo")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class cObjeto
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codigoField As String
        
        Private servicoField As String
        
        Private cepOrigemField As String
        
        Private cepDestinoField As String
        
        Private prazoEntregaField As Integer
        
        Private dataPostagemField As String
        
        Private dataPostagemCalculoField As String
        
        Private dataMaxEntregaField As String
        
        Private postagemDHField As String
        
        Private dataUltimoEventoField As String
        
        Private codigoUltimoEventoField As String
        
        Private tipoUltimoEventoField As String
        
        Private descricaoUltimoEventoField As String
        
        Private erroField As String
        
        Private msgErroField As String
        
        Private nuTicketField As String
        
        Private formaPagamentoField As String
        
        Private valorPagamentoField As String
        
        Private nuContratoField As String
        
        Private nuCartaoPostagemField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
                Me.RaisePropertyChanged("codigo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property servico() As String
            Get
                Return Me.servicoField
            End Get
            Set
                Me.servicoField = value
                Me.RaisePropertyChanged("servico")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property cepOrigem() As String
            Get
                Return Me.cepOrigemField
            End Get
            Set
                Me.cepOrigemField = value
                Me.RaisePropertyChanged("cepOrigem")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property cepDestino() As String
            Get
                Return Me.cepDestinoField
            End Get
            Set
                Me.cepDestinoField = value
                Me.RaisePropertyChanged("cepDestino")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property prazoEntrega() As Integer
            Get
                Return Me.prazoEntregaField
            End Get
            Set
                Me.prazoEntregaField = value
                Me.RaisePropertyChanged("prazoEntrega")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property dataPostagem() As String
            Get
                Return Me.dataPostagemField
            End Get
            Set
                Me.dataPostagemField = value
                Me.RaisePropertyChanged("dataPostagem")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property dataPostagemCalculo() As String
            Get
                Return Me.dataPostagemCalculoField
            End Get
            Set
                Me.dataPostagemCalculoField = value
                Me.RaisePropertyChanged("dataPostagemCalculo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property dataMaxEntrega() As String
            Get
                Return Me.dataMaxEntregaField
            End Get
            Set
                Me.dataMaxEntregaField = value
                Me.RaisePropertyChanged("dataMaxEntrega")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property postagemDH() As String
            Get
                Return Me.postagemDHField
            End Get
            Set
                Me.postagemDHField = value
                Me.RaisePropertyChanged("postagemDH")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property dataUltimoEvento() As String
            Get
                Return Me.dataUltimoEventoField
            End Get
            Set
                Me.dataUltimoEventoField = value
                Me.RaisePropertyChanged("dataUltimoEvento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property codigoUltimoEvento() As String
            Get
                Return Me.codigoUltimoEventoField
            End Get
            Set
                Me.codigoUltimoEventoField = value
                Me.RaisePropertyChanged("codigoUltimoEvento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property tipoUltimoEvento() As String
            Get
                Return Me.tipoUltimoEventoField
            End Get
            Set
                Me.tipoUltimoEventoField = value
                Me.RaisePropertyChanged("tipoUltimoEvento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property descricaoUltimoEvento() As String
            Get
                Return Me.descricaoUltimoEventoField
            End Get
            Set
                Me.descricaoUltimoEventoField = value
                Me.RaisePropertyChanged("descricaoUltimoEvento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=13)>  _
        Public Property erro() As String
            Get
                Return Me.erroField
            End Get
            Set
                Me.erroField = value
                Me.RaisePropertyChanged("erro")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=14)>  _
        Public Property msgErro() As String
            Get
                Return Me.msgErroField
            End Get
            Set
                Me.msgErroField = value
                Me.RaisePropertyChanged("msgErro")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=15)>  _
        Public Property nuTicket() As String
            Get
                Return Me.nuTicketField
            End Get
            Set
                Me.nuTicketField = value
                Me.RaisePropertyChanged("nuTicket")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=16)>  _
        Public Property formaPagamento() As String
            Get
                Return Me.formaPagamentoField
            End Get
            Set
                Me.formaPagamentoField = value
                Me.RaisePropertyChanged("formaPagamento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=17)>  _
        Public Property valorPagamento() As String
            Get
                Return Me.valorPagamentoField
            End Get
            Set
                Me.valorPagamentoField = value
                Me.RaisePropertyChanged("valorPagamento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=18)>  _
        Public Property nuContrato() As String
            Get
                Return Me.nuContratoField
            End Get
            Set
                Me.nuContratoField = value
                Me.RaisePropertyChanged("nuContrato")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=19)>  _
        Public Property nuCartaoPostagem() As String
            Get
                Return Me.nuCartaoPostagemField
            End Get
            Set
                Me.nuCartaoPostagemField = value
                Me.RaisePropertyChanged("nuCartaoPostagem")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class cResultadoObjeto
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private objetosField() As cObjeto
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property Objetos() As cObjeto()
            Get
                Return Me.objetosField
            End Get
            Set
                Me.objetosField = value
                Me.RaisePropertyChanged("Objetos")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface CalcPrecoPrazoWSSoapChannel
        Inherits WSCorreios.CalcPrecoPrazoWSSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CalcPrecoPrazoWSSoapClient
        Inherits System.ServiceModel.ClientBase(Of WSCorreios.CalcPrecoPrazoWSSoap)
        Implements WSCorreios.CalcPrecoPrazoWSSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function CalcPrecoPrazo(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String) As WSCorreios.cResultado Implements WSCorreios.CalcPrecoPrazoWSSoap.CalcPrecoPrazo
            Return MyBase.Channel.CalcPrecoPrazo(nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento)
        End Function
        
        Public Function CalcPrecoPrazoData(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal sDtCalculo As String) As WSCorreios.cResultado Implements WSCorreios.CalcPrecoPrazoWSSoap.CalcPrecoPrazoData
            Return MyBase.Channel.CalcPrecoPrazoData(nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento, sDtCalculo)
        End Function
        
        Public Function CalcPrecoPrazoRestricao(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal sDtCalculo As String) As WSCorreios.cResultado Implements WSCorreios.CalcPrecoPrazoWSSoap.CalcPrecoPrazoRestricao
            Return MyBase.Channel.CalcPrecoPrazoRestricao(nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento, sDtCalculo)
        End Function
        
        Public Function CalcPreco(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String) As WSCorreios.cResultado Implements WSCorreios.CalcPrecoPrazoWSSoap.CalcPreco
            Return MyBase.Channel.CalcPreco(nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento)
        End Function
        
        Public Function CalcPrecoData(ByVal nCdEmpresa As String, ByVal sDsSenha As String, ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal nVlPeso As String, ByVal nCdFormato As Integer, ByVal nVlComprimento As Decimal, ByVal nVlAltura As Decimal, ByVal nVlLargura As Decimal, ByVal nVlDiametro As Decimal, ByVal sCdMaoPropria As String, ByVal nVlValorDeclarado As Decimal, ByVal sCdAvisoRecebimento As String, ByVal sDtCalculo As String) As WSCorreios.cResultado Implements WSCorreios.CalcPrecoPrazoWSSoap.CalcPrecoData
            Return MyBase.Channel.CalcPrecoData(nCdEmpresa, sDsSenha, nCdServico, sCepOrigem, sCepDestino, nVlPeso, nCdFormato, nVlComprimento, nVlAltura, nVlLargura, nVlDiametro, sCdMaoPropria, nVlValorDeclarado, sCdAvisoRecebimento, sDtCalculo)
        End Function
        
        Public Function CalcPrazo(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String) As WSCorreios.cResultado Implements WSCorreios.CalcPrecoPrazoWSSoap.CalcPrazo
            Return MyBase.Channel.CalcPrazo(nCdServico, sCepOrigem, sCepDestino)
        End Function
        
        Public Function CalcPrazoData(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal sDtCalculo As String) As WSCorreios.cResultado Implements WSCorreios.CalcPrecoPrazoWSSoap.CalcPrazoData
            Return MyBase.Channel.CalcPrazoData(nCdServico, sCepOrigem, sCepDestino, sDtCalculo)
        End Function
        
        Public Function CalcPrazoRestricao(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String, ByVal sDtCalculo As String) As WSCorreios.cResultado Implements WSCorreios.CalcPrecoPrazoWSSoap.CalcPrazoRestricao
            Return MyBase.Channel.CalcPrazoRestricao(nCdServico, sCepOrigem, sCepDestino, sDtCalculo)
        End Function
        
        Public Function CalcPrecoFAC(ByVal nCdServico As String, ByVal nVlPeso As String, ByVal strDataCalculo As String) As WSCorreios.cResultado Implements WSCorreios.CalcPrecoPrazoWSSoap.CalcPrecoFAC
            Return MyBase.Channel.CalcPrecoFAC(nCdServico, nVlPeso, strDataCalculo)
        End Function
        
        Public Function CalcDataMaxima(ByVal codigoObjeto As String) As WSCorreios.cResultadoObjeto Implements WSCorreios.CalcPrecoPrazoWSSoap.CalcDataMaxima
            Return MyBase.Channel.CalcDataMaxima(codigoObjeto)
        End Function
        
        Public Function ListaServicos() As WSCorreios.cResultadoServicos Implements WSCorreios.CalcPrecoPrazoWSSoap.ListaServicos
            Return MyBase.Channel.ListaServicos
        End Function
        
        Public Function ListaServicosSTAR() As WSCorreios.cResultadoServicos Implements WSCorreios.CalcPrecoPrazoWSSoap.ListaServicosSTAR
            Return MyBase.Channel.ListaServicosSTAR
        End Function
        
        Public Function VerificaModal(ByVal nCdServico As String, ByVal sCepOrigem As String, ByVal sCepDestino As String) As WSCorreios.cResultadoModal Implements WSCorreios.CalcPrecoPrazoWSSoap.VerificaModal
            Return MyBase.Channel.VerificaModal(nCdServico, sCepOrigem, sCepDestino)
        End Function
        
        Public Function getVersao() As WSCorreios.versao Implements WSCorreios.CalcPrecoPrazoWSSoap.getVersao
            Return MyBase.Channel.getVersao
        End Function
    End Class
End Namespace
